apiVersion: batch/v1
kind: Job
metadata:
  name: doctrine-migrations
  namespace: pokemon
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ["sh", "-c", "until nc -z mariadb 3306; do echo 'En attente de MariaDB...'; sleep 3; done"]
      containers:
        - name: migrations
          image: ${REGISTRY}/pokemon-backend:latest
          imagePullPolicy: Always
          command: ["php", "bin/console", "doctrine:migrations:migrate", "--no-interaction", "--allow-no-migration"]
          env:
            - name: APP_ENV
              value: "prod"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: app-secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: database-url
            - name: CORS_ALLOW_ORIGIN
              value: "^https?://pokemon\\.portfolio-kdiochon\\.fr$"
