<?php

namespace ContainerW5JAbT4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XVK7_MeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xVK7.Me' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xVK7.Me'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\UserController::getUsers' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::getUsers()', 'getUserControllergetUsersService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'App\\Controller\\UserController::login' => ['privates', '.service_locator.gwZhsUg.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\UserController:getUsers' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::getUsers()', 'getUserControllergetUsersService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.5SuUxla.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'App\\Controller\\UserController:login' => ['privates', '.service_locator.gwZhsUg.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\UserController::getUsers' => '?',
            'App\\Controller\\UserController::register' => '?',
            'App\\Controller\\UserController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\UserController:getUsers' => '?',
            'App\\Controller\\UserController:register' => '?',
            'App\\Controller\\UserController:login' => '?',
        ]);
    }
}
