<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_users' => [[], ['_controller' => 'App\\Controller\\UserController::getUsers'], [], [['text', '/api/users']], [], [], []],
    'app_user_register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/users']], [], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/login']], [], [], []],
    'api_logout' => [[], ['_controller' => 'App\\Controller\\UserController::logout'], [], [['text', '/api/logout']], [], [], []],
    'App\Controller\UserController::getUsers' => [[], ['_controller' => 'App\\Controller\\UserController::getUsers'], [], [['text', '/api/users']], [], [], []],
    'App\Controller\UserController::register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/users']], [], [], []],
    'App\Controller\UserController::login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/login']], [], [], []],
    'App\Controller\UserController::logout' => [[], ['_controller' => 'App\\Controller\\UserController::logout'], [], [['text', '/api/logout']], [], [], []],
];
