apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp
  namespace: pokemon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: headlamp
    namespace: pokemon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: pokemon
  labels:
    app: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      serviceAccountName: headlamp
      containers:
        - name: headlamp
          image: ghcr.io/loft-sh/headlamp:v0.13.0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "200Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
              ephemeral-storage: "500Mi"
          ports:
            - containerPort: 8080
              name: http
          args:
            - "--host=0.0.0.0"
            - "--port=8080"
---
apiVersion: v1
kind: Service
metadata:
  name: headlamp
  namespace: pokemon
  labels:
    app: headlamp
spec:
  selector:
    app: headlamp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
